-- ----------------------------

-- PARTE 1: CRIAÇÃO DAS TABELAS

-- ----------------------------
DROP TABLE IF EXISTS Uf CASCADE;
DROP TABLE IF EXISTS Cidades CASCADE;
DROP TABLE IF EXISTS Profissoes CASCADE;
DROP TABLE IF EXISTS Bairros CASCADE;
DROP TABLE IF EXISTS Logradouros CASCADE;
DROP TABLE IF EXISTS Enderecos CASCADE;
DROP TABLE IF EXISTS Pessoas CASCADE;
DROP TABLE IF EXISTS Telefones CASCADE;
DROP TABLE IF EXISTS Categorias CASCADE;
DROP TABLE IF EXISTS Produtos CASCADE;
DROP TABLE IF EXISTS Compras CASCADE;
DROP TABLE IF EXISTS Itens_compras;
DROP TABLE IF EXISTS Vendas CASCADE;
DROP TABLE IF EXISTS Itens_Vendas CASCADE;

-- Tabela: uf

CREATE TABLE Uf (

    ID_UF INTEGER NOT NULL,

    NOME_ESTADO VARCHAR(20) NOT NULL,

    SIGLA VARCHAR(2) NOT NULL,

    PRIMARY KEY (ID_UF)

);



-- Tabela: Cidades

CREATE TABLE Cidades (

    ID_CIDADE INTEGER NOT NULL,

    NOME_CIDADE VARCHAR(255) NOT NULL,

    ID_UF INTEGER NOT NULL,

    PRIMARY KEY (ID_CIDADE)

);

CREATE TABLE Profissoes (

    ID_PROFISSAO INTEGER NOT NULL,

    NOME_PROFISSAO VARCHAR(20) NOT NULL,
    

    PRIMARY KEY (ID_PROFISSAO)

);

-- Tabela: Bairros

CREATE TABLE Bairros (

    ID_BAIRRO INTEGER NOT NULL,

    NOME_BAIRRO VARCHAR(255) NOT NULL,

    REGIAOCIDADE VARCHAR(255) NOT NULL,

    ID_CIDADE INTEGER NOT NULL,

    PRIMARY KEY (ID_BAIRRO)

);



-- Tabela: LOGAGRADOUROS

CREATE TABLE Logradouros (

    ID_LOGRADOURO INTEGER NOT NULL,

    TIPO INTEGER NOT NULL,

    LOGRADOURO VARCHAR(255) NOT NULL,

    CEP INTEGER NOT NULL,

    NUMEROINICIAL INTEGER,

    NUMEROFINAL INTEGER,

    ID_BAIRRO INTEGER NOT NULL,

    PRIMARY KEY (ID_LOGRADOURO)

);



-- Tabela: Enderecos

CREATE TABLE Enderecos (

    ID_ENDERECO INTEGER NOT NULL,

    ID_PESSOA INTEGER NOT NULL,

    ID_LOGRADOURO INTEGER NOT NULL,

    TIPO_ENDERECO INTEGER NOT NULL,

    COMPLEMENTO VARCHAR(255),

    PREFERENCIAL BIT NOT NULL,

    PRIMARY KEY (ID_ENDERECO)

);



-- Tabela: PESSOAS

CREATE TABLE Pessoas (

    ID_PESSOA INTEGER NOT NULL,

    ID_PROFISSAO INTEGER NOT NULL,

    TIPO_PESSOA INTEGER,

    NOME  VARCHAR(255),

    CPF_CNPJ  VARCHAR(255),

    SEXO  VARCHAR(255), -- Note: Definir na aplicação os tipos via combo

    RENDA DOUBLE PRECISION, 

    ESTADO_CIVIL VARCHAR(255), -- Note: Definir na aplicação os tipos via combo

    DATA_NASCIMENTO DATE,

    PRIMARY KEY (ID_PESSOA)

);



-- Tabela: Telefones

CREATE TABLE Telefones (

    ID_TELEFONE INTEGER NOT NULL,

    ID_PESSOA INTEGER NOT NULL,

    DDD INTEGER NOT NULL,

    TELEFONE VARCHAR(255) NOT NULL,

    TIPO INTEGER NOT NULL,

    PREFERENCIAL BIT NOT NULL,

    STATUS VARCHAR(1) NOT NULL,

    PRIMARY KEY (ID_TELEFONE)

);



-- Tabela: Categorias

CREATE TABLE Categorias (

    ID_CATEGORIA INTEGER NOT NULL,

    NOME_CATEGORIA VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID_CATEGORIA)

);



-- Tabela: Produtos

CREATE TABLE Produtos (

    ID_PRODUTO INTEGER NOT NULL,

    ID_CATEGORIA INTEGER NOT NULL,

    PRODUTO VARCHAR(255) NOT NULL,

    VALOR_VENDA DOUBLE PRECISION NOT NULL,

    PRIMARY KEY (ID_PRODUTO)

);



-- Tabela: Compras

CREATE TABLE Compras (

    ID_COMPRA INTEGER NOT NULL,

    DATA_PEDIDO DATE NOT NULL,

    DATA_ENTRADA DATE,

    ID_PESSOA INTEGER NOT NULL,

    PRIMARY KEY (ID_COMPRA)

);



-- Tabela: Itens_compras

CREATE TABLE Itens_compras (

    ID_ITEMCOMPRA INTEGER NOT NULL,

    ID_COMPRA INTEGER NOT NULL,

    ID_PRODUTO INTEGER NOT NULL,

    QUANTIDADE INTEGER NOT NULL,

    VLR_UNITARIO DOUBLE PRECISION NOT NULL,

    PRIMARY KEY (ID_ITEMCOMPRA)

);



-- Tabela: Vendas

CREATE TABLE Vendas (

    ID_VENDA INTEGER NOT NULL,

    ID_PESSOA INTEGER NOT NULL,

    DATA_VENDA DATE NOT NULL,

    DATA_FATURAMENTO DATE,

    TIPO_VENDA INTEGER NOT NULL,

    PRIMARY KEY (ID_VENDA)

);



-- Tabela: Itens_Vendas

CREATE TABLE Itens_Vendas (

    ID_ITEMVENDA INTEGER NOT NULL,

    ID_VENDA INTEGER NOT NULL,

    ID_PRODUTO INTEGER NOT NULL,

    QUANTIDADE INTEGER NOT NULL,

    VLR_UNITARIO DOUBLE PRECISION NOT NULL,

    PRIMARY KEY (ID_ITEMVENDA)

);



-- ----------------------------

-- PARTE 2: CHAVES ESTRANGEIRAS (FOREIGN KEYS)

-- ----------------------------



-- Tabela: Cidades

ALTER TABLE Cidades

    ADD CONSTRAINT Cidades_ID_UF_fkey

    FOREIGN KEY (ID_UF)

    REFERENCES Uf (ID_UF);



-- Tabela: Bairros

ALTER TABLE Bairros

    ADD CONSTRAINT Bairros_ID_CIDADE_fkey

    FOREIGN KEY (ID_CIDADE)

    REFERENCES Cidades (ID_CIDADE);



-- Tabela: LOGRADOUROS

ALTER TABLE Logradouros

    ADD CONSTRAINT CEP_ID_BAIRRO_fkey

    FOREIGN KEY (ID_BAIRRO)

    REFERENCES Bairros (ID_BAIRRO);



-- Tabela: Enderecos

ALTER TABLE Enderecos

    ADD CONSTRAINT Enderecos_ID_PESSOA_fkey

    FOREIGN KEY (ID_PESSOA)

    REFERENCES Pessoas (ID_PESSOA);



ALTER TABLE Enderecos

    ADD CONSTRAINT Enderecos_ID_Logradouro_fkey

    FOREIGN KEY (ID_LOGRADOURO)

    REFERENCES Logradouros (ID_LOGRADOURO);


-- Tabela: Telefones

ALTER TABLE Telefones

    ADD CONSTRAINT Telefones_ID_PESSOA_fkey

    FOREIGN KEY (ID_PESSOA)

    REFERENCES Pessoas (ID_PESSOA);


-- Tabela: Pessoas

ALTER TABLE Pessoas

    ADD CONSTRAINT Pessoas_ID_PROFISSAO_fkey

    FOREIGN KEY (ID_PROFISSAO)

    REFERENCES Profissoes (ID_PROFISSAO);



-- Tabela: Produtos

ALTER TABLE Produtos

    ADD CONSTRAINT Produtos_ID_CATEGORIA_fkey

    FOREIGN KEY (ID_CATEGORIA)

    REFERENCES Categorias (ID_CATEGORIA);



-- Tabela: Compras

ALTER TABLE Compras

    ADD CONSTRAINT Compras_ID_PESSOA_fkey

    FOREIGN KEY (ID_PESSOA)

    REFERENCES Pessoas (ID_PESSOA);



-- Tabela: Itens_compras

ALTER TABLE Itens_compras

    ADD CONSTRAINT Itens_compras_ID_COMPRA_fkey

    FOREIGN KEY (ID_COMPRA)

    REFERENCES Compras (ID_COMPRA);



ALTER TABLE Itens_compras

    ADD CONSTRAINT Itens_compras_ID_PRODUTO_fkey

    FOREIGN KEY (ID_PRODUTO)

    REFERENCES Produtos (ID_PRODUTO);



-- Tabela: Vendas

ALTER TABLE Vendas

    ADD CONSTRAINT Vendas_ID_PESSOA_fkey

    FOREIGN KEY (ID_PESSOA)

    REFERENCES PESSOAS (ID_PESSOA);



-- Tabela: Itens_Vendas

ALTER TABLE Itens_Vendas

    ADD CONSTRAINT Itens_Vendas_ID_VENDA_fkey

    FOREIGN KEY (ID_VENDA)

    REFERENCES Vendas (ID_VENDA);



ALTER TABLE Itens_Vendas

    ADD CONSTRAINT Itens_Vendas_ID_PRODUTO_fkey

    FOREIGN KEY (ID_PRODUTO)

    REFERENCES Produtos (ID_PRODUTO);